name: CMake on a single platform

on:
  push:
    branches: [ "master" ]

    paths:
      - 'CMakeLists.txt'
      - 'src/**'
      - 'tests/**'
      - 'include/**'
      - '.github/workflows/*.yml'

env:

  BUILD_TYPE: Release

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: check version
      run: cmake --version && g++ --version

    - name: Configure CMake
      working-directory: ${{github.workspace}}/tests

      run: cmake -S . -B build

    - name: Build
      working-directory: ${{github.workspace}}/tests

      run: cmake --build build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/tests/build

      run: ctest -C ${{env.BUILD_TYPE}} -V


  run-little-n-little-p:
    needs: [build]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        working-directory: ${{github.workspace}}

        run: cmake -S . -B build

      - name: Build
        working-directory: ${{github.workspace}}

        run: cmake --build build --config ${{env.BUILD_TYPE}}

      - name: Run
        working-directory: ${{github.workspace}}/build

        run: ./ggraph -n 100 -p 0.03 -o little_n_little_p.gml

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: little_n_little_p
          path: ${{github.workspace}}/build/little_n_little_p.gml

  run-little-n-big-p:
    needs: [build]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        working-directory: ${{github.workspace}}

        run: cmake -S . -B build

      - name: Build
        working-directory: ${{github.workspace}}

        run: cmake --build build --config ${{env.BUILD_TYPE}}

      - name: Run
        working-directory: ${{github.workspace}}/build

        run: ./ggraph -n 100 -p 0.3 -o little_n_big_p.gml

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: little_n_big_p
          path: ${{github.workspace}}/build/little_n_big_p.gml


  run-big-n-little-p:
    needs: [build]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        working-directory: ${{github.workspace}}

        run: cmake -S . -B build

      - name: Build
        working-directory: ${{github.workspace}}

        run: cmake --build build --config ${{env.BUILD_TYPE}}

      - name: Run
        working-directory: ${{github.workspace}}/build

        run: ./ggraph -n 1000 -p 0.001 -o big_n_little_p.gml

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: big_n_little_p
          path: ${{github.workspace}}/build/big_n_little_p.gml

  run-big-n-big-p:
    needs: [build]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        working-directory: ${{github.workspace}}

        run: cmake -S . -B build

      - name: Build
        working-directory: ${{github.workspace}}

        run: cmake --build build --config ${{env.BUILD_TYPE}}

      - name: Run
        working-directory: ${{github.workspace}}/build

        run: ./ggraph -n 1000 -p 0.3 -o big_n_big_p.gml

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: big_n_big_p
          path: ${{github.workspace}}/build/big_n_big_p.gml

  run-middle-n-middle-p:
    needs: [build]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        working-directory: ${{github.workspace}}

        run: cmake -S . -B build

      - name: Build
        working-directory: ${{github.workspace}}

        run: cmake --build build --config ${{env.BUILD_TYPE}}

      - name: Run
        working-directory: ${{github.workspace}}/build

        run: ./ggraph -n 500 -p 0.01 -o middle_n_middle_p.gml

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: middle_n_middle_p
          path: ${{github.workspace}}/build/middle_n_middle_p.gml

  upload:
    needs: [run-little-n-little-p, run-little-n-big-p, run-big-n-little-p, run-big-n-big-p, run-middle-n-middle-p]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Go to result branch
        run: |
          git checkout result
          git pull

      - name: Download
        uses: actions/download-artifact@v3.0.2
        with:
          name: little_n_little_p
          path: ${{github.workspace}}

      - name: Download
        uses: actions/download-artifact@v3.0.2
        with:
          name: little_n_big_p
          path: ${{github.workspace}}

      - name: Download
        uses: actions/download-artifact@v3.0.2
        with:
          name: big_n_little_p
          path: ${{github.workspace}}

      - name: Download
        uses: actions/download-artifact@v3.0.2
        with:
          name: big_n_big_p
          path: ${{github.workspace}}

      - name: Commit file
        working-directory: ${{github.workspace}}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -a -m "Results"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: result
          force: true



          
